other_variable:
  instance_type: other_variable
  params:
  - variable_name: CF1
    value:
      range: [0.01p,10.0p]
      step: "0.01p"
  - variable_name: CM1
    value:
      range: [0.01p,10.0p]
      step: "0.01p"
  - variable_name: CM2
    value:
      range: [0.01p,10.0p]
      step: "0.01p"
  - variable_name: RF1
    value:
      range: [1.0k,100.0k]
      step: "1.0k"
  - variable_name: RF2
    value:
      range: [1.0k,100.0k]
      step: "1.0k"
  - variable_name: VB1
    value:
      range: [0,1.2]
      step: "0.01"
  - variable_name: VB2
    value:
      range: [0,1.2]
      step: "0.01"
  - variable_name: VB4
    value:
      range: [0,1.2]
      step: "0.01"
M0:
  instance_type: pch_mac
  params:
  - variable_name: w_M0_per_finger
    value:
      range: [100.0u,200.0u]
      step: "100.0u"
  - variable_name: l_M0
    value:
      range: [0.13u,0.15u]
      step: "0.02u"
  - variable_name: nf_M0
    value:
      range: [20,25]
      step: "1"
M24:
  instance_type: pch_mac
  params:
  - variable_name: w_M24_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M24
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M24
    value:
      range: [1,20]
      step: "1"
M23:
  instance_type: pch_mac
  params:
  - variable_name: w_M23_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M23
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M23
    value:
      range: [1,20]
      step: "1"
M47:
  instance_type: pch_mac
  params:
  - variable_name: w_M47_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M47
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M47
    value:
      range: [1,20]
      step: "1"
M46:
  instance_type: pch_mac
  params:
  - variable_name: w_M46_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M46
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M46
    value:
      range: [1,20]
      step: "1"
M45:
  instance_type: pch_mac
  params:
  - variable_name: w_M45_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M45
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M45
    value:
      range: [1,20]
      step: "1"
M13:
  instance_type: pch_mac
  params:
  - variable_name: w_M13_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M13
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M13
    value:
      range: [1,20]
      step: "1"
M12:
  instance_type: pch_mac
  params:
  - variable_name: w_M12_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M12
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M12
    value:
      range: [1,20]
      step: "1"
M16:
  instance_type: pch_mac
  params:
  - variable_name: w_M16_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M16
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M16
    value:
      range: [1,20]
      step: "1"
M11:
  instance_type: pch_mac
  params:
  - variable_name: w_M11_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M11
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M11
    value:
      range: [1,20]
      step: "1"
M22:
  instance_type: nch_mac
  params:
  - variable_name: w_M22_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M22
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M22
    value:
      range: [1,20]
      step: "1"
M21:
  instance_type: nch_mac
  params:
  - variable_name: w_M21_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M21
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M21
    value:
      range: [1,20]
      step: "1"
M42:
  instance_type: nch_mac
  params:
  - variable_name: w_M42_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M42
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M42
    value:
      range: [1,20]
      step: "1"
M43:
  instance_type: nch_mac
  params:
  - variable_name: w_M43_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M43
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M43
    value:
      range: [1,20]
      step: "1"
M44:
  instance_type: nch_mac
  params:
  - variable_name: w_M44_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M44
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M44
    value:
      range: [1,20]
      step: "1"
M41:
  instance_type: nch_mac
  params:
  - variable_name: w_M41_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M41
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M41
    value:
      range: [1,20]
      step: "1"
M18:
  instance_type: nch_mac
  params:
  - variable_name: w_M18_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M18
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M18
    value:
      range: [1,20]
      step: "1"
M17:
  instance_type: nch_mac
  params:
  - variable_name: w_M17_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M17
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M17
    value:
      range: [1,20]
      step: "1"
M14:
  instance_type: nch_mac
  params:
  - variable_name: w_M14_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M14
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M14
    value:
      range: [1,20]
      step: "1"
M15:
  instance_type: nch_mac
  params:
  - variable_name: w_M15_per_finger
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: l_M15
    value:
      range: [0.2u,10.0u]
      step: "0.1u"
  - variable_name: nf_M15
    value:
      range: [1,20]
      step: "1"
